### PR TITLE
#6 enable config hot reload

### PR DESCRIPTION
**Pull request by JennieJi**
Summary of what I did:  Watch given config file. If it changed, clear type registration, config cache, and build again, update endpoint mappings & tables, print fancy messages. Pretty straight forward.  

What I didn't do: check config file dependencies in this MR.

Result screenshot:
screen shot 2018-08-19 at 10 29 05 pm

### CODE REVIEW

**Comment by Cryrivers** [comment]
@JennieJi could help redo this commit on latest `master`? I have problem merging 2 branches.

**Comment by JennieJi** [comment]
@Cryrivers so sad that I found `runtime` has changed it's behaviour?  
I met 2 issues when trying to rebase my branch:
* I used `MantaStyle.clearTypes` to remove all the registered types, but I cannot find it anymore.   
* Master branch build fail now. Error msg:
```bash
lerna ERR! yarn run build stdout:
$ tsc -p tsconfig.json
src/index.ts(108,26): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'TypeAliasDeclaration' has no compatible call signatures.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Cryrivers** [comment]
yeah could you check the last commit on master? We just removed the magic Query type. Replaced with a normal type. I had problem on both rebasing and merging this branch. Thinking easier if we branch out and redo this PR again.

**Comment by Cryrivers** [comment]
Oh btw lihau’s LazyTypeDeclaration make us able to remove the type registry completely.

**Comment by Cryrivers** [comment]
For building issue, I think you could do lerna clean, lerna bootstrap and lerna exec yarn build again

**Comment by JennieJi** [comment]
@Cryrivers all conflicts resolved. And `clear()` is also added

**Comment by Cryrivers** [comment]
stO Jennie master

**Comment by JennieJi** [comment]
what is stO?

**Comment by Cryrivers** [comment]
Orz but in the opposite direction

**Pull request merged**
