### PR TITLE
Annotation System Syntax Upgrade

### PR DESCRIPTION
**Pull request by tanhauhau**
Annotation now uses [handlebar](https://handlebarsjs.com/) syntax
You annotate your type with `@mantastyle <handlebar here>`

For example:
```
type User = {
  /**
   * @mantastyle {{faker "{{internet.userName}}"}}
   */
  userName: string,
  /**
   * @mantastyle {{range 5 10}}
   */
  age: number,
  /**
   * @mantastyle {{example "Happy Birthday"
   *                        (qotd)
   *                        (faker "Merry Christmas {{internet.username}}")
   * }}
   */
  message: string,
};
```

TODO:
- [x] ~~Backward compatible?~~
- [ ] Plugin rename: `plugin-mock-example` to `plugin-mock-random`
- [ ] Custom build in plugin
   - [ ] `@length` for array
   - [ ] `@key` for type literal
- [ ] Lazy evaluate of annotation
   - refer to example above, right now `qotd` and `faker` is called everytime even though `example` did not choose them.

### CODE REVIEW

**Comment by Cryrivers** [comment]
lol i'm way behind..given up already..

**Comment by Cryrivers** [comment]
too fast to fix typos 🤣

**Comment by tanhauhau** [comment]
lol. im stuck now. don't know how to link this with our current code... 😵

**Comment by Cryrivers** [comment]
i feel we dont have to make it backward compatible..dont think it's very possible.

**Pull request closed without merging**
